{{- if .Values.controller.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubernetes-ingress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
    helm.sh/chart: {{ template "kubernetes-ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "kubernetes-ingress.imagePullSecret" . }}
{{- end }}
