apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes-ingress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
    helm.sh/chart: {{ template "kubernetes-ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
{{- if .Values.controller.service.labels }}
{{ toYaml .Values.controller.service.labels | indent 4 }}
{{- end }}
  annotations:
{{- range $key, $value := .Values.controller.service.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  {{ with .Values.controller.service.clusterIP }}clusterIP: {{ . }}{{ end }}
  type: {{ .Values.controller.service.type }}
  ports:
    - name: http
      port: {{ .Values.controller.service.ports.http }}
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.http }}
    - name: https
      port: {{ .Values.controller.service.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.https }}
    - name: stat
      port: {{ .Values.controller.service.ports.stat }}
      protocol: TCP
      targetPort: {{ .Values.controller.service.targetPorts.stat }}
  selector:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  externalIPs:
{{- if .Values.controller.service.externalIPs }}
{{ toYaml .Values.controller.service.externalIPs | indent 4 }}
{{- end -}}
{{- if (eq .Values.controller.service.type "LoadBalancer") }}
{{- if .Values.controller.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.controller.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.controller.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.controller.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- end }}

