apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes-ingress.defaultBackend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.name" . }}
    helm.sh/chart: {{ template "kubernetes-ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  clusterIP: None 
  ports:
    - name: http
      port: {{ .Values.defaultBackend.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ template "kubernetes-ingress.defaultBackend.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
